services:
    client:
      build:
        context: .
        dockerfile: Dockerfile.client
      image: react-flask-app-client
      ports:
        - "80:80"
  
    api:
      build:
        context: .
        dockerfile: Dockerfile.api
      image: react-flask-app-api
      
