services:
    client:
      build:
        context: .
        dockerfile: Dockerfile.client
      image: react-flask-app-client
      container_name: client 
      restart: unless-stopped
      ports:
        - "80:80"
  
    api:
      build:
        context: .
        dockerfile: Dockerfile.api
      image: react-flask-app-api
      container_name: api
      restart: unless-stopped
      
